DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS managers;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS order_details;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS pictures;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(30) NOT NULL,
  password varchar(45) NOT NULL,
  role enum('CUSTOMER','MANAGER') NOT NULL
);

CREATE TABLE managers (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int DEFAULT NULL,
  name varchar(30) NOT NULL,
  surname varchar(30) NOT NULL,
  middle_name varchar(30) DEFAULT NULL,
  address varchar(45) DEFAULT NULL,
  phone_number varchar(18) DEFAULT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE customers (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int NOT NULL,
  name varchar(30) NOT NULL,
  surname varchar(30) NOT NULL,
  middle_name varchar(30) DEFAULT NULL,
  address varchar(45) DEFAULT NULL,
  phone_number varchar(18) DEFAULT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE categories (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name enum('GRAPHICS_CARD','CPU','RAM','MOTHERBOARD','POWER_SUPPLY') NOT NULL
);

CREATE TABLE products (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(45) NOT NULL,
  category_id int DEFAULT NULL,
  price decimal(10,2) DEFAULT NULL,
  stock int DEFAULT NULL,
  stock_Min int DEFAULT NULL,
  stock_max int DEFAULT NULL,
  description varchar(500),
  FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
);

CREATE TABLE product_pictures (
  product_id int NOT NULL,
  sequence int NOT NULL,
  url varchar(255) NOT NULL,
  PRIMARY KEY (product_id, url),
  FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE orders (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id int NOT NULL,
  order_date date DEFAULT NULL,
  status enum('PENDING','READY','PROCESSING','COMPLETED','CANCELED') NOT NULL,
  FOREIGN KEY (customer_id) REFERENCES customers(id)
);

CREATE TABLE order_details (
  product_id int NOT NULL,
  order_id int NOT NULL,
  amount int DEFAULT NULL,
  PRIMARY KEY (product_id,order_id),
  FOREIGN KEY (order_id) REFERENCES orders(id),
  FOREIGN KEY (product_id) REFERENCES products(id)
);